# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dorm_diy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QWidget


class Ui_dorm_diy(QWidget):

    def __init__(self):
        super(Ui_dorm_diy,self).__init__()
        self.setupUi(self)

    def setupUi(self, dorm_diy):
        dorm_diy.setObjectName("dorm_diy")
        dorm_diy.resize(454, 430)
        self.verticalLayoutWidget = QtWidgets.QWidget(dorm_diy)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 391, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.diy_dorm_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.diy_dorm_label.setObjectName("diy_dorm_label")
        self.verticalLayout.addWidget(self.diy_dorm_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.div_service_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.div_service_label.setObjectName("div_service_label")
        self.horizontalLayout.addWidget(self.div_service_label)
        self.timeEdit = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        self.timeEdit.setWrapping(False)
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout.addWidget(self.timeEdit)
        self.diy_dorm_bolang_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.diy_dorm_bolang_label.setObjectName("diy_dorm_bolang_label")
        self.horizontalLayout.addWidget(self.diy_dorm_bolang_label)
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.horizontalLayout.addWidget(self.timeEdit_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.div_dorm_change_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.div_dorm_change_btn.setObjectName("div_dorm_change_btn")
        self.verticalLayout.addWidget(self.div_dorm_change_btn)
        self.verticalLayout.setStretch(0, 9)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(dorm_diy)
        QtCore.QMetaObject.connectSlotsByName(dorm_diy)

    def retranslateUi(self, dorm_diy):
        _translate = QtCore.QCoreApplication.translate
        dorm_diy.setWindowTitle(_translate("dorm_diy", "Form"))
        self.diy_dorm_label.setText(_translate("dorm_diy", "TextLabel"))
        self.div_service_label.setText(_translate("dorm_diy", "晚出时间范围："))
        self.diy_dorm_bolang_label.setText(_translate("dorm_diy", "~"))
        self.div_dorm_change_btn.setText(_translate("dorm_diy", "修改为..."))

class MyMainForm(QMainWindow, Ui_dorm_diy):
    def __init__(self, parent=None):
        super(MyMainForm, self).__init__(parent)
        self.setupUi(self)

if __name__ == '__main__':
    # 每一个pyqt程序中都需要有一个QApplication对象，sys.argv是一个命令行参数列表
    app = QApplication(sys.argv)
    # 实例化窗口
    form = MyMainForm()
    # 将窗口控件显示在屏幕上
    form.show()
    # 进入程序的主循环，遇到退出情况，终止程序
    sys.exit(app.exec_())