# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
import sys


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(450, 300)
        login.setMinimumSize(QtCore.QSize(450, 300))
        login.setMaximumSize(QtCore.QSize(450, 300))
        login.setStyleSheet("#login{background-image: url(:/new/prefix1/images/login_bg.jpg);}")
        self.verticalLayoutWidget = QtWidgets.QWidget(login)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 50, 314, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(30, -1, 30, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.user_id_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.user_id_label.setObjectName("user_id_label")
        self.horizontalLayout_3.addWidget(self.user_id_label)
        self.user_id_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.user_id_edit.setMinimumSize(QtCore.QSize(50, 15))
        self.user_id_edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.user_id_edit.setObjectName("user_id_edit")
        self.horizontalLayout_3.addWidget(self.user_id_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(30, -1, 30, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.user_pwd_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.user_pwd_label.setObjectName("user_pwd_label")
        self.horizontalLayout_4.addWidget(self.user_pwd_label)
        self.user_pwd_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.user_pwd_edit.setObjectName("user_pwd_edit")
        self.horizontalLayout_4.addWidget(self.user_pwd_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.code_login_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.code_login_btn.setObjectName("code_login_btn")
        self.horizontalLayout_5.addWidget(self.code_login_btn)
        self.face_login_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.face_login_btn.setObjectName("face_login_btn")
        self.horizontalLayout_5.addWidget(self.face_login_btn)
        self.reg_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.reg_btn.setObjectName("reg_btn")
        self.horizontalLayout_5.addWidget(self.reg_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "校园防御系统"))
        self.user_id_label.setText(_translate("login", "登录口令："))
        self.user_pwd_label.setText(_translate("login", "登陆密码："))
        self.code_login_btn.setText(_translate("login", "口令登录"))
        self.face_login_btn.setText(_translate("login", "人脸登录"))
        self.reg_btn.setText(_translate("login", "注册"))

class MyMainForm(QMainWindow, Ui_login):
    def __init__(self, parent=None):
        super(MyMainForm, self).__init__(parent)
        self.setupUi(self)

if __name__ == '__main__':
    # 每一个pyqt程序中都需要有一个QApplication对象，sys.argv是一个命令行参数列表
    app = QApplication(sys.argv)
    # 实例化窗口
    form = MyMainForm()
    # 将窗口控件显示在屏幕上
    form.show()
    # 进入程序的主循环，遇到退出情况，终止程序
    sys.exit(app.exec_())